<?php

namespace Arcanely\Editor;

class Editor
{
    // This can be aliased and used anywhere.
    public static function fakeData() {
        return '{"time":1634504995454,"blocks":[{"id":"DsJreSGa0y","type":"header","data":{"text":"Welcome","level":2,"anchor":"welcome"}},{"id":"B5WDZQgo1L","type":"paragraph","data":{"text":"Here is some <mark class=\"cdx-marker\">text</mark> that is <b>bold</b>, <u class=\"cdx-underline\">underlined</u>, and <i>italicized</i> and also some <code class=\"inline-code\">inline code</code>.&nbsp;"}},{"id":"puzqHbdcna","type":"nestedList","data":{"style":"ordered","items":[{"content":"Lists","items":[]},{"content":"can be ordered","items":[{"content":"and nested","items":[]}]}]}},{"id":"K4RepwObvC","type":"paragraph","data":{"text":"Or"}},{"id":"eWkgIoj8Rw","type":"nestedList","data":{"style":"unordered","items":[{"content":"We can have","items":[]},{"content":"Unordered lists","items":[]}]}},{"id":"Xx3aF1Q37m","type":"delimiter","data":{}},{"id":"qUB_teuDVp","type":"paragraph","data":{"text":"After the delimiter, we can use checklists."}},{"id":"3W3JPJ_SLu","type":"checklist","data":{"items":[{"text":"Buy Milk","checked":false},{"text":"Finish this package","checked":true}]}},{"id":"AgYwuKsCUb","type":"quote","data":{"text":"This summer, I teached a whale to jump out if its tail!","caption":"some kid","alignment":"left"}},{"id":"pXYidQLFjj","type":"paragraph","data":{"text":"We\'ve got multiple alert types"}},{"id":"LBbRyloKKB","type":"alert","data":{"type":"primary","message":"Primary"}},{"id":"NipLZ9mr-C","type":"alert","data":{"type":"secondary","message":"Secondary"}},{"id":"9xwDITORhh","type":"alert","data":{"type":"info","message":"Info"}},{"id":"eK-j28rCnL","type":"alert","data":{"type":"success","message":"Success"}},{"id":"r69AuGLueK","type":"alert","data":{"type":"warning","message":"Warning"}},{"id":"cgD0rZ5up3","type":"alert","data":{"type":"danger","message":"Danger"}},{"id":"ChiQo5iv7z","type":"alert","data":{"type":"light","message":"Light"}},{"id":"4ZwnDOMmrI","type":"alert","data":{"type":"dark","message":"Dark"}},{"id":"ZLkTGKl827","type":"paragraph","data":{"text":"Here\'s a button."}},{"id":"FqZAKwAvXZ","type":"AnyButton","data":{"link":"https://example.com","text":"Click Me"}},{"id":"zVHCkPkR_o","type":"table","data":{"withHeadings":true,"content":[["Type","APR"],["Auto","20%"],["Motorcycle","21%"]]}},{"id":"jUeoCQD7Bi","type":"raw","data":{"html":"<div style=\"color: red;\">Raw HTML</div>"}},{"id":"7xwL3us4yt","type":"code","data":{"code":"<?php\nclass CodeExample {\n  public $language;\n  __construct($language) {\n    $this->language = $language\n  }\n}"}},{"id":"AazIwQViju","type":"paragraph","data":{"text":"Let\'s show a <a href=\"https://google.com\">link</a> example as well."}},{"id":"2viN2WbU5O","type":"image","data":{"url":"https://media4.giphy.com/media/GGOO8NJNh5kty/giphy.gif","caption":"We can drag these images in here from other websites.","withBorder":true,"withBackground":true,"stretched":false}}],"version":"2.22.2"}';
    }
}
